### PR TITLE
Msw fix

### LINKED ISSUE #21: Review fixes of #20

### PR DESCRIPTION
**Pull request by borangoher**
close #21. This PR should now only display the relevant changes.

### CODE REVIEW

File: src/api/index.js [hunk 1]
```diff
@@ -0,0 +1,15 @@
+export const loginUser = async (userData) => {
+  const res = await fetch("/login", {
```
Comment (ozgunbal) [inline src/api/index.js:2]: better to not shorten variable names in general. `response` is more understandable for everyone rather than `res`

File: src/api/index.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+    method: "POST",
+    mode: "cors",
+    body: JSON.stringify(userData),
+    headers: {
+      "Content-Type": "application/json",
+    },
+  });
+
+  if (!res.ok) {
+    throw Error("Failed to log in");
```
Comment (ozgunbal) [inline src/api/index.js:12]: Looks like your current logic inside `Login.js`'s `onSubmit` is not working right. First try to send 40X status code response via msw handler. You shouldn't allow user to login. Plus, better to display error message to user not only `console.error`

**Review by ozgunbal — CHANGES_REQUESTED** [review]

File: src/mocks/handlers.js [hunk 3]
```diff
@@ -1,12 +1,19 @@
 import { rest } from "msw";
 
 export const handlers = [
-  rest.post("http://localhost:8080/login", async (req, res, ctx) => {
-    console.log(req);
+  rest.post("/login", async (req, res, ctx) => {
+    const userData = await req.json().then();
```
Comment (ozgunbal) [inline src/mocks/handlers.js:5]: if you're using async/await, you don't need `.then()`

**Review by ozgunbal — APPROVED** [review]
